name: DeployToGitHubPages
env:
  PUBLISH_DIR: bin/Release/net6.0/publish/wwwroot
  # Include subfolders if needed

on:
  push:
    branches: 
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        # include-prerelease: true

    - name: Publish app
      run: dotnet publish -c Release -f net6.0
      # You can use cd before if your project is in a subfolder

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /BlazorSwitchControl/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        repo: ${{ secrets.GH_PAGES_DEV_REPO }}
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
